# Generated by Django 3.2 on 2021-05-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
